import React, { useEffect, useRef, useState } from 'react';
import { Text, View } from 'react-native';
import { api } from '../../api';
import { readSmall, writeSmall } from '../../archive';
import { useTask } from '../../task';
import FilePicker, { Upload } from '../../FilePicker';
import Recorder from '../../Recorder';
import AudioPlayer from '../../AudioPlayer';
import OutputActions, { downloadBlob } from '../../OutputActions';
import Markdown from '../../Markdown';
import { Button, Busy, Card, Choices, Field, Notice, PageHeading, styles } from '../../ui';
import { historyForm, voiceForm } from './contracts.mjs';
import type { AudioDocument, HistoryItem, Language, Reference, Turn, TutorResponse } from './types';
const newSessionId = () => typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16);});
function Sources({ references }: { references: Reference[] }) {
  const [expanded,setExpanded]=useState(false);
  return references.length?<View style={{gap:8}}><Button secondary label={expanded?'Hide source excerpts':`Sources (${references.length})`} onPress={()=>setExpanded(v=>!v)} />{expanded&&references.map((ref,index)=><View key={index} style={{gap:4}}><Text style={styles.label}>{ref.filename}{ref.page!=null?` · PAGE ${ref.page}`:''}</Text><Text selectable style={styles.body}>{ref.excerpt}</Text><Text style={styles.subtitle}>Relevance: {Math.round(ref.score*100)}%</Text></View>)}</View>:null;
}
function TurnCard({ turn, update }: { turn: Turn; update: (value: Turn) => void }) {
  const [audio,setAudio]=useState<Blob|null>(null),[info,setInfo]=useState('');const task=useTask();
  const saveHistory=async(signal:AbortSignal,blob?:Blob)=>{const history=await api<HistoryItem>('audio','/api/v1/history',historyForm(turn,blob),{signal});update({...turn,historyId:history.id,historyError:undefined});};
  return <Card><Text style={styles.label}>YOU · {turn.language.toUpperCase()}</Text><Markdown text={turn.question} /><View style={{height:1,backgroundColor:'#E2DDD3'}} /><Text style={styles.label}>TUTOR</Text><Markdown text={turn.answer} /><Sources references={turn.references} /><OutputActions text={`${turn.question}\n\n${turn.answer}`} name="tutor-conversation" />
    <View style={styles.row}><Button secondary label={audio?'Regenerate spoken answer':'Listen to answer'} disabled={task.busy} onPress={()=>task.run(async signal=>{
      const blob=await api<Blob>('audio','/api/v1/voice/tts',{text:turn.answer,language:turn.language},{signal,blob:true});setAudio(blob);
      if(turn.historyId){try{const body=new FormData();body.append('audio_file',blob,'answer.wav');await api('audio',`/api/v1/history/${encodeURIComponent(turn.historyId)}/audio`,body,{signal,method:'PUT'});setInfo('Spoken answer saved to your history.');}catch(e){setInfo(`Audio is ready; saving it to history failed: ${e instanceof Error?e.message:'Please retry.'}`);}}
    })} />{!turn.historyId&&<Button secondary label="Save to history" disabled={task.busy} onPress={()=>task.run(signal=>saveHistory(signal,audio||undefined))} />}{audio&&<Button secondary label="Download answer audio" onPress={()=>downloadBlob(audio,'tutor-answer.wav')} />}</View>{audio&&<AudioPlayer blob={audio} />}<Text style={styles.subtitle}>{turn.historyId?'Saved in audio history.':turn.historyError||'Not yet saved in backend history.'}</Text><Notice text={info} />{task.busy&&<Busy text="Preparing your spoken answer…" />}<Notice text={task.error} error />
  </Card>;
}
function SavedHistory({ item, open }: { item: HistoryItem; open: () => void }) {
  const [audio,setAudio]=useState<Blob|null>(null),[expanded,setExpanded]=useState(false);const task=useTask();
  return <Card><Text style={styles.heading}>{item.question}</Text><Text style={styles.subtitle}>{item.language} · {new Date(item.created_at).toLocaleString()}</Text><View style={styles.row}><Button secondary label={expanded?'Hide answer':'Read answer'} onPress={()=>setExpanded(v=>!v)} /><Button secondary label="Continue this topic" onPress={open} />{item.has_audio&&<Button secondary label="Load saved audio" disabled={task.busy} onPress={()=>task.run(async signal=>setAudio(await api('audio',`/api/v1/history/${encodeURIComponent(item.id)}/audio`,undefined,{signal,blob:true})))} />}</View>{expanded&&<><Markdown text={item.answer} /><Sources references={item.references} /><OutputActions text={`${item.question}\n\n${item.answer}`} name="saved-tutor-answer" /></>}{audio&&<><AudioPlayer blob={audio} /><Button secondary label="Download saved audio" onPress={()=>downloadBlob(audio,'saved-answer.wav')} /></>}{task.busy&&<Busy />}<Notice text={task.error} error /></Card>;
}
export default function AudioTutor({ userId, preview = false }: { userId: string; preview?: boolean }) {
  const [tab,setTab]=useState('Tutor'),[language,setLanguage]=useState<Language>('english'),[question,setQuestion]=useState(''),[rawTranscript,setRawTranscript]=useState(''),[corrected,setCorrected]=useState(''),[grounded,setGrounded]=useState('General biology'),[voiceMode,setVoiceMode]=useState('Review transcript'),[turns,setTurns]=useState<Turn[]>([]),[docs,setDocs]=useState<AudioDocument[]>([]),[history,setHistory]=useState<HistoryItem[]>([]),[sessionId,setSessionId]=useState(newSessionId),[confirmDelete,setConfirmDelete]=useState<string|null>(null),[info,setInfo]=useState(''),[ready,setReady]=useState(false),[storageError,setStorageError]=useState('');
  const task=useTask(), restored=useRef(false);
  useEffect(()=>{if(preview){setReady(true);return;}let mounted=true;void readSmall<{turns:Turn[];language:Language;sessionId:string}>('audio-draft',userId).then(saved=>{if(mounted&&saved){setTurns(saved.turns);setLanguage(saved.language);setSessionId(saved.sessionId);}}).catch(e=>{if(mounted)setStorageError(String(e));}).finally(()=>{if(mounted){restored.current=true;setReady(true);}});return()=>{mounted=false;};},[userId,preview]);
  useEffect(()=>{if(!preview&&restored.current)void writeSmall('audio-draft',userId,{turns:turns.slice(-30),language,sessionId}).catch(e=>setStorageError(e instanceof Error?e.message:'Conversation could not be saved locally.'));},[turns,language,sessionId,userId,preview]);
  const update=(turn:Turn)=>setTurns(v=>v.map(t=>t.id===turn.id?turn:t));
  const append=async(text:string,response:TutorResponse,signal:AbortSignal)=>{
    const turn:Turn={id:`turn-${Date.now()}-${Math.random().toString(36).slice(2)}`,createdAt:new Date().toISOString(),question:text,answer:response.answer,language,references:response.references||[]};setTurns(v=>[...v,turn]);setQuestion('');setRawTranscript('');setCorrected('');
    try{const item=await api<HistoryItem>('audio','/api/v1/history',historyForm(turn),{signal});update({...turn,historyId:item.id});}catch(e){update({...turn,historyError:`Text answer is ready; history could not be saved: ${e instanceof Error?e.message:'Please retry.'}`});}
  };
  const transcribe=(file:Upload)=>task.run(async signal=>{
    setInfo('');const body=voiceForm(file,language,voiceMode==='Direct document voice answer'&&grounded==='My documents'?sessionId:undefined);
    if(voiceMode==='Direct document voice answer'&&grounded==='My documents'){
      const response=await api<TutorResponse&{transcript:string;session_id:string}>('audio','/api/v1/voice/query',body,{signal});if(response.session_id)setSessionId(response.session_id);await append(response.transcript,response,signal);
    }else{const response=await api<{transcript:string;detected_language:string}>('audio','/api/v1/voice/transcribe',body,{signal});setQuestion(response.transcript);setRawTranscript(response.transcript);setCorrected('');setInfo(`Transcript ready. Detected language: ${response.detected_language}. Review it before asking.`);}
  });
  const upload=(file:Upload)=>task.run(async signal=>{const body=new FormData();body.append('file',file.file,file.name);await api('audio','/api/v1/documents/upload',body,{signal});setDocs(await api('audio','/api/v1/documents/',undefined,{signal}));setInfo(`${file.name} indexed successfully.`);});
  return <View style={styles.page}><PageHeading eyebrow="04 / CONVERSATIONAL REVIEW" title="Talk it through." description="Your independent audio learning workspace: multilingual voice questions, document study, tutor conversations and saved spoken answers." /><Choices values={['Tutor','My documents','Saved history']} selected={tab} onChange={v=>{setTab(v);if(v==='Saved history')void task.run(async signal=>setHistory(await api('audio','/api/v1/history',undefined,{signal})));}} /><Notice text={info} /><Notice text={storageError} error />
    {tab==='My documents'&&<Card><Text style={styles.heading}>Your audio study library</Text><FilePicker disabled={task.busy} accept=".pdf,.pptx,.docx,.xlsx,.txt,.md" onPick={upload} /><Button secondary label="Refresh documents" disabled={task.busy} onPress={()=>task.run(async signal=>setDocs(await api('audio','/api/v1/documents/',undefined,{signal})))} />{docs.map(doc=><View key={doc.document_id} style={{gap:8}}><Text style={styles.body}>{doc.filename}</Text><Text style={styles.subtitle}>{doc.file_type} · {doc.chunk_count} chunks · {new Date(doc.uploaded_at).toLocaleDateString()}</Text><View style={styles.row}><Button secondary label="Study my documents" onPress={()=>{setGrounded('My documents');setTab('Tutor');}} /><Button secondary label={confirmDelete===doc.document_id?'Confirm document deletion':'Delete document'} disabled={task.busy} onPress={()=>{if(confirmDelete!==doc.document_id){setConfirmDelete(doc.document_id);return;}void task.run(async signal=>{await api('audio',`/api/v1/documents/${encodeURIComponent(doc.document_id)}`,undefined,{signal,method:'DELETE'});setDocs(v=>v.filter(d=>d.document_id!==doc.document_id));setConfirmDelete(null);setInfo('Document removed from the audio library.');});}} />{confirmDelete===doc.document_id&&<Button secondary label="Cancel deletion" onPress={()=>setConfirmDelete(null)} />}</View>{confirmDelete===doc.document_id&&<Notice text="This removes the document from the audio backend and its search index. Confirm only if you want to delete it." />}</View>)}{!docs.length&&<Text style={styles.subtitle}>No documents loaded. Refresh the library or upload study material.</Text>}</Card>}
    {tab==='Saved history'&&<><Button secondary label="Refresh audio history" disabled={task.busy} onPress={()=>task.run(async signal=>setHistory(await api('audio','/api/v1/history',undefined,{signal})))} />{history.map(item=><SavedHistory key={item.id} item={item} open={()=>{setSessionId(newSessionId());setLanguage(item.language);setTurns([{id:item.id,question:item.question,answer:item.answer,language:item.language,references:item.references,createdAt:item.created_at,historyId:item.id}]);setTab('Tutor');setQuestion('');setCorrected('');setRawTranscript('');}} />)}{!history.length&&<Card><Text style={styles.subtitle}>No saved audio history loaded yet.</Text></Card>}</>}
    {tab==='Tutor'&&<><Card><Choices values={['english','tamil','sinhala']} selected={language} onChange={v=>setLanguage(v as Language)} /><Choices values={['General biology','My documents','Muscle tutor']} selected={grounded} onChange={setGrounded} />{grounded==='My documents'&&<><Text style={styles.subtitle}>Answers use your audio library. Upload documents or review them in My documents.</Text><FilePicker disabled={task.busy} accept=".pdf,.pptx,.docx,.xlsx,.txt,.md" onPick={upload} /></>}
    {grounded==='Muscle tutor'&&<View style={{gap:10}}><Text style={styles.heading}>Explore human muscles</Text>{['Pectoralis major','Deltoid','Biceps brachii','Triceps brachii','Quadriceps femoris'].map(muscle=><Button key={muscle} secondary label={muscle} onPress={()=>{setQuestion(`Explain the origin, insertion, action and innervation of the ${muscle}.`);setCorrected('');}} />)}<Text style={styles.subtitle}>Choose a muscle, then ask a follow-up about its anatomy or function. The response follows your selected language.</Text></View>}
    <Choices values={['Review transcript',...(grounded==='My documents'?['Direct document voice answer']:[])]} selected={grounded==='My documents'?voiceMode:'Review transcript'} onChange={setVoiceMode} /><Recorder disabled={task.busy||!ready} onRecorded={file=>{if(grounded!=='My documents'&&voiceMode!=='Review transcript')setVoiceMode('Review transcript');void transcribe(file);}} /><Text style={styles.label}>OR UPLOAD AN AUDIO QUESTION</Text><FilePicker disabled={task.busy||!ready} accept="audio/*" onPick={transcribe} /><Field label="YOUR QUESTION / REVIEWED TRANSCRIPT" value={question} onChange={v=>{setQuestion(v);setCorrected('');}} multiline placeholder="Why does our breathing rate increase during exercise?" />{!!rawTranscript&&rawTranscript!==question&&<Text selectable style={styles.subtitle}>Original transcript: {rawTranscript}</Text>}
    <View style={styles.row}><Button label="Ask tutor ↗" disabled={task.busy||!ready||!question.trim()} onPress={()=>task.run(async signal=>{setInfo('');const text=question.trim();const response=await api<TutorResponse>('audio','/api/v1/documents/ask',{transcript:rawTranscript||text,enhanced_query:corrected|| (rawTranscript&&rawTranscript!==text?text:undefined),language,session_id:sessionId,document_grounded:grounded==='My documents'},{signal});await append(text,response,signal);})} /><Button secondary label="Fix transcript" disabled={task.busy||!ready||!question.trim()} onPress={()=>task.run(async signal=>{const response=await api<{enhanced_query:string}>('audio','/api/v1/documents/enhance',{transcript:question,language},{signal});if(!rawTranscript)setRawTranscript(question);setCorrected(response.enhanced_query);setQuestion(response.enhanced_query);})} /><Button secondary label="New conversation" disabled={task.busy||!ready} onPress={()=>{setSessionId(newSessionId());setTurns([]);setQuestion('');setRawTranscript('');setCorrected('');setInfo('');}} /></View>
    <View style={styles.row}><Button secondary label="Create saved backend session" disabled={task.busy||!ready} onPress={()=>task.run(async signal=>{const response=await api<{session_id:string}>('audio',`/api/v1/sessions/?language=${language}`,{}, {signal});setSessionId(response.session_id);setInfo('A new backend session is ready.');})} /><Button secondary label="Check current session" disabled={task.busy||!ready} onPress={()=>task.run(async signal=>{const response=await api<{language:string;messages:unknown[]}>('audio',`/api/v1/sessions/${encodeURIComponent(sessionId)}`,undefined,{signal});setInfo(`Session loaded in ${response.language}. ${response.messages.length} messages returned; your current conversation is kept separately in this workspace.`);})} /></View></Card>
    {!turns.length&&<Card><Text style={styles.heading}>Start with a question.</Text><Text style={styles.subtitle}>Record your voice, upload audio, or type a question. Your answer and source excerpts will appear here.</Text></Card>}{turns.map(turn=><TurnCard key={turn.id} turn={turn} update={update} />)}</>}
    {task.busy&&<Busy text="Working with your audio tutor…" />}<Notice text={task.error} error />
  </View>;
}
