import React from 'react';
import { Platform, Pressable, Text, useWindowDimensions, View } from 'react-native';
import { modules, type Page } from '../navigation';
import { Button, Card, colors, styles } from '../ui';

export default function Dashboard({ name, open }: { name: string; open: (page: Page) => void }) {
  const { width } = useWindowDimensions();
  return <View style={styles.page}><View style={styles.row}><Text style={styles.label}>YOUR PERSONAL BIOLOGY WORKSPACE</Text><View style={{ flex: 1 }} /><Text style={styles.subtitle}>G.C.E. A/L Biology</Text></View><View style={{ gap: 12, paddingVertical: 12 }}><Text style={[styles.title, { fontSize: width > 700 ? 46 : 34, fontFamily: Platform.OS === 'web' ? 'Georgia, serif' : undefined, fontWeight: '400' }]}>A little curiosity.{'\n'} A deeper understanding.</Text><Text style={[styles.subtitle, { maxWidth: 570 }]}>Welcome{name ? `, ${name}` : ''}. Explore a concept, test what you know, or give your study notes a fresh perspective.</Text></View>
    <Card style={{ backgroundColor: '#EBE4D7B0', padding: 28 }}><View style={styles.row}><View style={{ flex: 1, minWidth: 210, gap: 10 }}><Text style={styles.label}>YOUR NEXT LEARNING MOMENT</Text><Text style={[styles.heading, { fontSize: 24 }]}>How would you like to learn today?</Text><Text style={styles.subtitle}>Four ways to explore. One connected experience.</Text></View><Button label="Explore a concept ↗" onPress={() => open('visual')} /></View></Card>
    <View style={styles.row}><Text style={styles.heading}>Your learning toolkit</Text><View style={{ flex: 1 }} /><Text style={styles.subtitle}>04 connected experiences</Text></View>
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 18 }}>{modules.map(module => <Pressable key={module.id} accessibilityRole="button" accessibilityLabel={`Open ${module.label}`} onPress={() => open(module.id)} style={(state) => ({ width: width >= 1000 ? '48.8%' : '100%', transform: [{ translateY: ('hovered' in state && state.hovered) ? -3 : 0 }] })}><Card style={{ height: '100%', minHeight: 236 }}><View style={styles.row}><View style={{ backgroundColor: module.tint, width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }}><Text style={{ fontSize: 30, color: colors.ink }}>{module.icon}</Text></View><View style={{ flex: 1 }} /><Text style={{ fontSize: 23, color: colors.muted }}>↗</Text></View><Text style={styles.label}>{module.subtitle}</Text><Text style={[styles.heading, { fontSize: 23 }]}>{module.label}</Text><Text style={styles.subtitle}>{module.description}</Text><Text style={{ color: '#9A7260', fontSize: 12 }}>{module.tag}</Text></Card></Pressable>)}</View>
    <Text style={[styles.subtitle, { textAlign: 'center', fontSize: 12 }]}>Built for thoughtful learning · BioLearnX · R26-SE-041</Text></View>;
}
