import React, { useState } from 'react';
import { Platform, Pressable, ScrollView, Text, View } from 'react-native';
import { auth } from '../auth';
import { Button, Card, colors, Field, Notice, styles } from '../ui';

export default function Login({ explore }: { explore: () => void }) {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [name, setName] = useState(''), [mode, setMode] = useState('Sign in'), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState('');
  const submit = async () => {
    if (!auth) return; setBusy(true); setError(''); setMessage('');
    try {
      const redirect = Platform.OS === 'web' ? window.location.origin : undefined;
      const response = mode === 'Create account' ? await auth.auth.signUp({ email: email.trim(), password, options: { data: { full_name: name.trim() }, emailRedirectTo: redirect } }) : mode === 'Reset password' ? await auth.auth.resetPasswordForEmail(email.trim(), { redirectTo: redirect }) : await auth.auth.signInWithPassword({ email: email.trim(), password });
      if (response.error) throw response.error;
      if (mode !== 'Sign in') setMessage(mode === 'Reset password' ? 'Check your email for a password reset link.' : 'Account created. If email confirmation is enabled, check your inbox before signing in.');
    } catch (e) { setError(e instanceof Error ? e.message : 'Unable to authenticate.'); } finally { setBusy(false); }
  };
  return <ScrollView contentContainerStyle={{ minHeight: '100%', padding: 28, justifyContent: 'center', alignItems: 'center' }}><View style={{ width: '100%', maxWidth: 1000, flexDirection: 'row', flexWrap: 'wrap', gap: 48, alignItems: 'center' }}><View style={{ flex: 1, minWidth: 270, gap: 24 }}><Text style={{ fontSize: 27, color: colors.ink, fontWeight: '600' }}>✳ BioLearnX</Text><Text style={[styles.title, { fontSize: 46, fontWeight: '400', fontFamily: Platform.OS === 'web' ? 'Georgia, serif' : undefined }]}>Understand more.{'\n'}Learn your way.</Text><Text style={styles.subtitle}>A calmer space for biology. Visualize ideas, practice with purpose, recover your notes, and talk through the things that make you curious.</Text><View style={styles.row}>{['Visuals', 'Practice', 'Notes', 'Audio'].map(label => <Text key={label} style={{ color: colors.accent, padding: 9, backgroundColor: '#EEDDD680', borderRadius: 9 }}>{label}</Text>)}</View></View><Card style={{ flex: 1, minWidth: 280, maxWidth: 420, padding: 32 }}><Text style={styles.label}>ONE ACCOUNT. FOUR WAYS TO LEARN.</Text><Text style={[styles.heading, { fontSize: 27 }]}>{mode === 'Sign in' ? 'Welcome back.' : mode}</Text><Text style={styles.subtitle}>Your biology workspace is waiting.</Text>{!auth && <Notice text="Shared login needs your common Supabase Auth URL and public publishable/anon key in .env.local. See README.md to connect your services." />}{mode === 'Create account' && <Field label="FULL NAME" value={name} onChange={setName} />}<Field label="EMAIL ADDRESS" value={email} onChange={setEmail} placeholder="you@university.edu" />{mode !== 'Reset password' && <Field label="PASSWORD" value={password} onChange={setPassword} secure />}<Notice text={error} error /><Notice text={message} /><Button label={busy ? 'Please wait…' : mode} disabled={!auth || busy || !email.trim() || (mode !== 'Reset password' && !password)} onPress={submit} /><View style={styles.row}>{['Sign in', 'Create account', 'Reset password'].filter(v => v !== mode).map(v => <Pressable key={v} accessibilityRole="button" onPress={() => { setMode(v); setError(''); setMessage(''); }}><Text style={{ color: colors.accent, fontSize: 12 }}>{v}</Text></Pressable>)}</View><Button secondary label="Preview the workspace" onPress={explore} /></Card></View></ScrollView>;
}
