import React, { useState } from 'react';
import { Image, Modal, Pressable, Text, View } from 'react-native';
import { api } from '../../api';
import { listArchive, removeArchive, saveArchive } from '../../archive';
import { useTask } from '../../task';
import FilePicker, { Upload } from '../../FilePicker';
import OutputActions from '../../OutputActions';
import { Button, Busy, Card, Choices, Field, Notice, PageHeading, styles } from '../../ui';
interface OcrLine { crop_b64: string; raw_text: string; visual_text?: string; final_text: string; confidence: number }
interface Result { original_b64?: string; enhanced_b64?: string; extracted_text?: string; extracted_text_ta?: string; extracted_text_en?: string; lines?: OcrLine[]; context_improved?: boolean }
interface SavedNotes { id: string; createdAt: string; title: string; mime: string; mode: string; result: Result }
function LineCorrection({ line, index }: { line: OcrLine; index: number }) {
  const [text, setText] = useState(line.final_text), [saved, setSaved] = useState(false); const task = useTask();
  return <Card style={{ padding: 18 }}><Text style={styles.label}>LINE {index+1} · CONFIDENCE {Math.round(line.confidence*100)}%</Text>{!!line.crop_b64&&<Image source={{uri:`data:image/png;base64,${line.crop_b64}`}} accessibilityLabel={`Handwritten line ${index+1}`} style={{height:85,width:'100%'}} resizeMode="contain" />}<Text selectable style={styles.subtitle}>Raw OCR: {line.raw_text}</Text><Field label={`CORRECTED TEXT FOR LINE ${index+1}`} value={text} onChange={v=>{setText(v);setSaved(false);}} multiline /><Text style={styles.subtitle}>Submitting stores this image crop and corrected text in the OCR backend's research dataset.</Text><Button secondary label={saved?'Correction saved':'Submit OCR correction'} disabled={task.busy||!line.crop_b64||!text.trim()||saved} onPress={()=>task.run(async signal=>{await api('notes','/api/feedback/ocr',{crop_b64:line.crop_b64,corrected_text:text.trim()},{signal});setSaved(true);})} />{task.busy&&<Busy />}<Notice text={task.error} error /></Card>;
}
export default function Notes({ userId }: { userId: string }) {
  const [tab,setTab]=useState('Process image'),[mode,setMode]=useState('Enhance + OCR + translate'),[file,setFile]=useState<Upload|null>(null),[saved,setSaved]=useState<SavedNotes|null>(null),[language,setLanguage]=useState('Sinhala'),[archive,setArchive]=useState<SavedNotes[]>([]),[info,setInfo]=useState(''),[zoom,setZoom]=useState<string|null>(null);
  const task=useTask(), result=saved?.result;
  const text=language==='Sinhala'?result?.extracted_text:language==='Tamil'?result?.extracted_text_ta:result?.extracted_text_en;
  return <View style={styles.page}><PageHeading eyebrow="03 / IMAGE TO NOTES" title="Give your notes a fresh start." description="Enhance handwriting, recover Sinhala text and explore available translations. This workspace keeps its own images, results and local archive." /><Choices values={['Process image','Saved results']} selected={tab} onChange={v=>{setTab(v);if(v==='Saved results')void task.run(async()=>setArchive(await listArchive('notes',userId)));}} /><Notice text={info} />
    {tab==='Saved results'?<Card><Text style={styles.heading}>Your local image-to-notes archive</Text><Text style={styles.subtitle}>Up to 30 results, stored only for this account in this browser.</Text><Button secondary label="Refresh saved results" disabled={task.busy} onPress={()=>task.run(async()=>setArchive(await listArchive('notes',userId)))} />{archive.map(item=><View key={item.id} style={{gap:8}}><Text style={styles.body}>{item.title}</Text><Text style={styles.subtitle}>{item.mode} · {new Date(item.createdAt).toLocaleString()}</Text><View style={styles.row}><Button label="Open result" onPress={()=>{setSaved(item);setFile(null);setTab('Process image');}} /><Button secondary label="Remove local entry" disabled={task.busy} onPress={()=>task.run(async()=>{await removeArchive('notes',userId,item.id);setArchive(v=>v.filter(a=>a.id!==item.id));})} /></View></View>)}{!archive.length&&<Text style={styles.subtitle}>No results saved yet.</Text>}</Card>:<>
    <Card><Text style={styles.heading}>Choose your processing flow</Text><Choices values={['Enhance + OCR + translate','Enhance only','OCR only']} selected={mode} onChange={setMode} /><FilePicker disabled={task.busy} accept="image/png,image/jpeg,image/webp,image/bmp" onPick={v=>{setFile(v);setSaved(null);setInfo('');}} /><Text style={styles.subtitle}>{file?.name||'Upload a handwritten Sinhala page. Use OCR only for an already clear image.'}</Text><View style={styles.row}><Button label={mode==='Enhance only'?'Enhance image':mode==='OCR only'?'Extract text':'Process page ↗'} disabled={!file||task.busy} onPress={()=>task.run(async signal=>{
      if(!file)return;setSaved(null);setInfo('');const body=new FormData();body.append('file',file.file,file.name);
      const response=await api<Result>('notes',mode==='Enhance only'?'/api/enhance':mode==='OCR only'?'/api/ocr':'/api/process',body,{signal});
      const item:SavedNotes={id:`notes-${Date.now()}`,createdAt:new Date().toISOString(),title:file.name,mime:file.file.type||'image/jpeg',mode,result:response};setSaved(item);
      try{await saveArchive('notes',userId,item);}catch(e){setInfo(e instanceof Error?e.message:'Result is available, but could not be archived.');}
    })} /><Button secondary label="Clear current page" disabled={task.busy} onPress={()=>{setFile(null);setSaved(null);setInfo('');}} /></View></Card>
    {result&&saved&&<><View style={styles.row}>{(['original_b64','enhanced_b64'] as const).filter(key=>!!result[key]).map(key=><Card key={key} style={{flex:1,minWidth:240}}><Text style={styles.label}>{key==='original_b64'?'ORIGINAL PAGE':'ENHANCED PAGE'}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Enlarge ${key==='original_b64'?'original':'enhanced'} image`} onPress={()=>setZoom(`data:${key==='original_b64'?saved.mime:'image/png'};base64,${result[key]}`)}><Image accessibilityLabel={key==='original_b64'?'Original handwritten page':'Enhanced handwritten page'} source={{uri:`data:${key==='original_b64'?saved.mime:'image/png'};base64,${result[key]}`}} style={{height:330,width:'100%'}} resizeMode="contain" /></Pressable><OutputActions image={result[key]} name={`${saved.title.replace(/\.[^.]+$/,'')}-${key==='original_b64'?'original':'enhanced'}`} mime={key==='original_b64'?saved.mime:'image/png'} /></Card>)}</View>
    {result.extracted_text!==undefined&&<Card><Text style={styles.heading}>Recovered text</Text><Choices values={['Sinhala','Tamil','English']} selected={language} onChange={setLanguage} /><Text selectable style={styles.body}>{text?.trim()|| (language==='Sinhala'?'No Sinhala text detected. Try a clearer image.':'Translation was not returned by the service.')}</Text>{!!text?.trim()&&<><Text style={styles.subtitle}>{text.split(/\s+/).filter(Boolean).length} words</Text><OutputActions text={text} name={`${saved.title.replace(/\.[^.]+$/,'')}-${language.toLowerCase()}`} /></>}<Text style={styles.subtitle}>{result.lines?.length??0} line results. Check recovered text against your source before using it for study.</Text>{result.context_improved===false&&<Text style={styles.subtitle}>This result contains OCR and translations; contextual note synthesis was not applied by the backend.</Text>}<OutputActions text={JSON.stringify(result,null,2)} name="ocr-result" /></Card>}
    {!!result.lines?.length&&<View style={{gap:16}}><Text style={styles.heading}>Line confidence & corrections</Text>{result.lines.map((line,index)=><LineCorrection key={`${saved.id}-${index}`} line={line} index={index} />)}</View>}</>}
    </>}{task.busy&&<Busy text="Working with your image-to-notes service…" />}<Notice text={task.error} error />
    <Modal visible={!!zoom} transparent animationType="fade" onRequestClose={()=>setZoom(null)}><View style={{flex:1,backgroundColor:'#302E2AEF',padding:24,gap:16}}><Button label="Close image" onPress={()=>setZoom(null)} />{zoom&&<Image source={{uri:zoom}} style={{flex:1,width:'100%'}} resizeMode="contain" />}</View></Modal>
  </View>;
}
